### PR TITLE
Update file to create PR

### PR DESCRIPTION
**Pull request by ryanholder**

### CODE REVIEW

**Comment by le-bott** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.kibana-PRs/26/

**Build Log**
*last 50 lines*

 ```
[...truncated 412 lines...]
File tmp/app/partials/load.html created.
File tmp/app/partials/modal.html created.
File tmp/app/partials/paneladd.html created.
File tmp/app/partials/paneleditor.html created.
File tmp/app/partials/panelgeneral.html created.
File tmp/app/partials/querySelect.html created.
File tmp/app/partials/roweditor.html created.

Running "cssmin:build" (cssmin) task
File tmp/app/panels/bettermap/leaflet/leaflet.css created.
File tmp/app/panels/bettermap/leaflet/leaflet.ie.css created.
File tmp/app/panels/bettermap/leaflet/plugins.css created.
File tmp/app/panels/bettermap/module.css created.
File tmp/app/panels/query/query.css created.
File tmp/css/animate.min.css created.
File tmp/css/bootstrap-responsive.min.css created.
File tmp/css/bootstrap.dark.min.css created.
File tmp/css/bootstrap.light.min.css created.
File tmp/css/font-awesome.min.css created.
File tmp/css/normalize.min.css created.
File tmp/css/timepicker.css created.
File tmp/vendor/bootstrap/less/tests/css-tests.css created.

Running "ngmin:build" (ngmin) task
ngminifying tmp/app/controllers/all.js, tmp/app/controllers/dash.js, tmp/app/controllers/dashLoader.js, tmp/app/controllers/pulldown.js, tmp/app/controllers/row.js, tmp/app/directives/addPanel.js, tmp/app/directives/all.js, tmp/app/directives/arrayJoin.js, tmp/app/directives/configModal.js, tmp/app/directives/confirmClick.js, tmp/app/directives/dashUpload.js, tmp/app/directives/esVersion.js, tmp/app/directives/kibanaPanel.js, tmp/app/directives/kibanaSimplePanel.js, tmp/app/directives/ngBlur.js, tmp/app/directives/ngModelOnBlur.js, tmp/app/directives/resizable.js, tmp/app/directives/tip.js, tmp/app/services/alertSrv.js, tmp/app/services/all.js, tmp/app/services/dashboard.js, tmp/app/services/esVersion.js, tmp/app/services/fields.js, tmp/app/services/filterSrv.js, tmp/app/services/kbnIndex.js, tmp/app/services/panelMove.js, tmp/app/services/querySrv.js, tmp/app/services/timer.js, tmp/app/filters/all.js, tmp/app/panels/bettermap/leaflet/leaflet-src.js, tmp/app/panels/bettermap/leaflet/leaflet.js, tmp/app/panels/bettermap/leaflet/plugins.js, tmp/app/panels/bettermap/module.js, tmp/app/panels/column/module.js, tmp/app/panels/dashcontrol/module.js, tmp/app/panels/derivequeries/module.js, tmp/app/panels/fields/module.js, tmp/app/panels/filtering/module.js, tmp/app/panels/goal/module.js, tmp/app/panels/histogram/interval.js, tmp/app/panels/histogram/module.js, tmp/app/panels/histogram/timeSeries.js, tmp/app/panels/hits/module.js, tmp/app/panels/map/lib/jquery.jvectormap.min.js, tmp/app/panels/map/lib/map.europe.js, tmp/app/panels/map/lib/map.usa.js, tmp/app/panels/map/lib/map.world.js, tmp/app/panels/map/module.js, tmp/app/panels/query/module.js, tmp/app/panels/sparklines/interval.js, tmp/app/panels/sparklines/module.js, tmp/app/panels/sparklines/timeSeries.js, tmp/app/panels/stats/module.js, tmp/app/panels/table/module.js, tmp/app/panels/terms/module.js, tmp/app/panels/text/lib/showdown.js, tmp/app/panels/text/module.js, tmp/app/panels/timepicker/module.js, tmp/app/panels/trends/module.js, tmp/app/app.js, tmp/vendor/angular/angular-cookies.js, tmp/vendor/angular/angular-dragdrop.js, tmp/vendor/angular/angular-sanitize.js, tmp/vendor/angular/angular-strap.js, tmp/vendor/angular/angular.js, tmp/vendor/angular/bindonce.js, tmp/vendor/angular/datepicker.js, tmp/vendor/angular/timepicker.js, tmp/vendor/elasticjs/elastic-angular-client.js

Running "requirejs:build" (requirejs) task

Running "clean:temp" (clean) task
Cleaning tmp...OK

Running "build:write_revision" task

Running "git-describe:me" (git-describe) task
>> v3.0.0-125-8cd212e

Running "string-replace:config" (string-replace) task
File dist/app/components/require.config.js created.
File dist/app/app.js created.

Running "uglify:dest" (uglify) task
[TypeError: Cannot assign to read only property 'warnings' of true]
>> Uglifying source "dist/app/app.js" failed.
Warning: Uglification failed.
Cannot assign to read only property 'warnings' of true. 
 Use --force to continue.

Aborted due to warnings.
Build step 'Execute shell' marked build as failure
```
Test FAILed.

**Comment by le-bott** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.kibana-PRs/27/

**Build Log**
*last 50 lines*

 ```
[...truncated 136 lines...]
File tmp/app/partials/load.html created.
File tmp/app/partials/modal.html created.
File tmp/app/partials/paneladd.html created.
File tmp/app/partials/paneleditor.html created.
File tmp/app/partials/panelgeneral.html created.
File tmp/app/partials/querySelect.html created.
File tmp/app/partials/roweditor.html created.

Running "cssmin:build" (cssmin) task
File tmp/app/panels/bettermap/leaflet/leaflet.css created.
File tmp/app/panels/bettermap/leaflet/leaflet.ie.css created.
File tmp/app/panels/bettermap/leaflet/plugins.css created.
File tmp/app/panels/bettermap/module.css created.
File tmp/app/panels/query/query.css created.
File tmp/css/animate.min.css created.
File tmp/css/bootstrap-responsive.min.css created.
File tmp/css/bootstrap.dark.min.css created.
File tmp/css/bootstrap.light.min.css created.
File tmp/css/font-awesome.min.css created.
File tmp/css/normalize.min.css created.
File tmp/css/timepicker.css created.
File tmp/vendor/bootstrap/less/tests/css-tests.css created.

Running "ngmin:build" (ngmin) task
ngminifying tmp/app/controllers/all.js, tmp/app/controllers/dash.js, tmp/app/controllers/dashLoader.js, tmp/app/controllers/pulldown.js, tmp/app/controllers/row.js, tmp/app/directives/addPanel.js, tmp/app/directives/all.js, tmp/app/directives/arrayJoin.js, tmp/app/directives/configModal.js, tmp/app/directives/confirmClick.js, tmp/app/directives/dashUpload.js, tmp/app/directives/esVersion.js, tmp/app/directives/kibanaPanel.js, tmp/app/directives/kibanaSimplePanel.js, tmp/app/directives/ngBlur.js, tmp/app/directives/ngModelOnBlur.js, tmp/app/directives/resizable.js, tmp/app/directives/tip.js, tmp/app/services/alertSrv.js, tmp/app/services/all.js, tmp/app/services/dashboard.js, tmp/app/services/esVersion.js, tmp/app/services/fields.js, tmp/app/services/filterSrv.js, tmp/app/services/kbnIndex.js, tmp/app/services/panelMove.js, tmp/app/services/querySrv.js, tmp/app/services/timer.js, tmp/app/filters/all.js, tmp/app/panels/bettermap/leaflet/leaflet-src.js, tmp/app/panels/bettermap/leaflet/leaflet.js, tmp/app/panels/bettermap/leaflet/plugins.js, tmp/app/panels/bettermap/module.js, tmp/app/panels/column/module.js, tmp/app/panels/dashcontrol/module.js, tmp/app/panels/derivequeries/module.js, tmp/app/panels/fields/module.js, tmp/app/panels/filtering/module.js, tmp/app/panels/goal/module.js, tmp/app/panels/histogram/interval.js, tmp/app/panels/histogram/module.js, tmp/app/panels/histogram/timeSeries.js, tmp/app/panels/hits/module.js, tmp/app/panels/map/lib/jquery.jvectormap.min.js, tmp/app/panels/map/lib/map.europe.js, tmp/app/panels/map/lib/map.usa.js, tmp/app/panels/map/lib/map.world.js, tmp/app/panels/map/module.js, tmp/app/panels/query/module.js, tmp/app/panels/sparklines/interval.js, tmp/app/panels/sparklines/module.js, tmp/app/panels/sparklines/timeSeries.js, tmp/app/panels/stats/module.js, tmp/app/panels/table/module.js, tmp/app/panels/terms/module.js, tmp/app/panels/text/lib/showdown.js, tmp/app/panels/text/module.js, tmp/app/panels/timepicker/module.js, tmp/app/panels/trends/module.js, tmp/app/app.js, tmp/vendor/angular/angular-cookies.js, tmp/vendor/angular/angular-dragdrop.js, tmp/vendor/angular/angular-sanitize.js, tmp/vendor/angular/angular-strap.js, tmp/vendor/angular/angular.js, tmp/vendor/angular/bindonce.js, tmp/vendor/angular/datepicker.js, tmp/vendor/angular/timepicker.js, tmp/vendor/elasticjs/elastic-angular-client.js

Running "requirejs:build" (requirejs) task

Running "clean:temp" (clean) task
Cleaning tmp...OK

Running "build:write_revision" task

Running "git-describe:me" (git-describe) task
>> v3.0.0-126-5671213

Running "string-replace:config" (string-replace) task
File dist/app/components/require.config.js created.
File dist/app/app.js created.

Running "uglify:dest" (uglify) task
[TypeError: Cannot assign to read only property 'warnings' of true]
>> Uglifying source "dist/app/app.js" failed.
Warning: Uglification failed.
Cannot assign to read only property 'warnings' of true. 
 Use --force to continue.

Aborted due to warnings.
Build step 'Execute shell' marked build as failure
```
Test FAILed.

**Comment by ryanholder** [comment]
retest this please

**Comment by le-bott** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.kibana-PRs/28/

**Build Log**
*last 50 lines*

 ```
[...truncated 512 lines...]
File tmp/app/partials/load.html created.
File tmp/app/partials/modal.html created.
File tmp/app/partials/paneladd.html created.
File tmp/app/partials/paneleditor.html created.
File tmp/app/partials/panelgeneral.html created.
File tmp/app/partials/querySelect.html created.
File tmp/app/partials/roweditor.html created.

Running "cssmin:build" (cssmin) task
File tmp/app/panels/bettermap/leaflet/leaflet.css created.
File tmp/app/panels/bettermap/leaflet/leaflet.ie.css created.
File tmp/app/panels/bettermap/leaflet/plugins.css created.
File tmp/app/panels/bettermap/module.css created.
File tmp/app/panels/query/query.css created.
File tmp/css/animate.min.css created.
File tmp/css/bootstrap-responsive.min.css created.
File tmp/css/bootstrap.dark.min.css created.
File tmp/css/bootstrap.light.min.css created.
File tmp/css/font-awesome.min.css created.
File tmp/css/normalize.min.css created.
File tmp/css/timepicker.css created.
File tmp/vendor/bootstrap/less/tests/css-tests.css created.

Running "ngmin:build" (ngmin) task
ngminifying tmp/app/controllers/all.js, tmp/app/controllers/dash.js, tmp/app/controllers/dashLoader.js, tmp/app/controllers/pulldown.js, tmp/app/controllers/row.js, tmp/app/directives/addPanel.js, tmp/app/directives/all.js, tmp/app/directives/arrayJoin.js, tmp/app/directives/configModal.js, tmp/app/directives/confirmClick.js, tmp/app/directives/dashUpload.js, tmp/app/directives/esVersion.js, tmp/app/directives/kibanaPanel.js, tmp/app/directives/kibanaSimplePanel.js, tmp/app/directives/ngBlur.js, tmp/app/directives/ngModelOnBlur.js, tmp/app/directives/resizable.js, tmp/app/directives/tip.js, tmp/app/services/alertSrv.js, tmp/app/services/all.js, tmp/app/services/dashboard.js, tmp/app/services/esVersion.js, tmp/app/services/fields.js, tmp/app/services/filterSrv.js, tmp/app/services/kbnIndex.js, tmp/app/services/panelMove.js, tmp/app/services/querySrv.js, tmp/app/services/timer.js, tmp/app/filters/all.js, tmp/app/panels/bettermap/leaflet/leaflet-src.js, tmp/app/panels/bettermap/leaflet/leaflet.js, tmp/app/panels/bettermap/leaflet/plugins.js, tmp/app/panels/bettermap/module.js, tmp/app/panels/column/module.js, tmp/app/panels/dashcontrol/module.js, tmp/app/panels/derivequeries/module.js, tmp/app/panels/fields/module.js, tmp/app/panels/filtering/module.js, tmp/app/panels/goal/module.js, tmp/app/panels/histogram/interval.js, tmp/app/panels/histogram/module.js, tmp/app/panels/histogram/timeSeries.js, tmp/app/panels/hits/module.js, tmp/app/panels/map/lib/jquery.jvectormap.min.js, tmp/app/panels/map/lib/map.europe.js, tmp/app/panels/map/lib/map.usa.js, tmp/app/panels/map/lib/map.world.js, tmp/app/panels/map/module.js, tmp/app/panels/query/module.js, tmp/app/panels/sparklines/interval.js, tmp/app/panels/sparklines/module.js, tmp/app/panels/sparklines/timeSeries.js, tmp/app/panels/stats/module.js, tmp/app/panels/table/module.js, tmp/app/panels/terms/module.js, tmp/app/panels/text/lib/showdown.js, tmp/app/panels/text/module.js, tmp/app/panels/timepicker/module.js, tmp/app/panels/trends/module.js, tmp/app/app.js, tmp/vendor/angular/angular-cookies.js, tmp/vendor/angular/angular-dragdrop.js, tmp/vendor/angular/angular-sanitize.js, tmp/vendor/angular/angular-strap.js, tmp/vendor/angular/angular.js, tmp/vendor/angular/bindonce.js, tmp/vendor/angular/datepicker.js, tmp/vendor/angular/timepicker.js, tmp/vendor/elasticjs/elastic-angular-client.js

Running "requirejs:build" (requirejs) task

Running "clean:temp" (clean) task
Cleaning tmp...OK

Running "build:write_revision" task

Running "git-describe:me" (git-describe) task
>> v3.0.0-126-5671213

Running "string-replace:config" (string-replace) task
File dist/app/components/require.config.js created.
File dist/app/app.js created.

Running "uglify:dest" (uglify) task
[TypeError: Cannot assign to read only property 'warnings' of true]
>> Uglifying source "dist/app/app.js" failed.
Warning: Uglification failed.
Cannot assign to read only property 'warnings' of true. 
 Use --force to continue.

Aborted due to warnings.
Build step 'Execute shell' marked build as failure
```
Test FAILed.

**Comment by mrdavidlaing** [comment]
retest this please

**Comment by le-bott** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.kibana-PRs/29/

**Build Log**
*last 50 lines*

 ```
[...truncated 519 lines...]
File tmp/app/partials/load.html created.
File tmp/app/partials/modal.html created.
File tmp/app/partials/paneladd.html created.
File tmp/app/partials/paneleditor.html created.
File tmp/app/partials/panelgeneral.html created.
File tmp/app/partials/querySelect.html created.
File tmp/app/partials/roweditor.html created.

Running "cssmin:build" (cssmin) task
File tmp/app/panels/bettermap/leaflet/leaflet.css created.
File tmp/app/panels/bettermap/leaflet/leaflet.ie.css created.
File tmp/app/panels/bettermap/leaflet/plugins.css created.
File tmp/app/panels/bettermap/module.css created.
File tmp/app/panels/query/query.css created.
File tmp/css/animate.min.css created.
File tmp/css/bootstrap-responsive.min.css created.
File tmp/css/bootstrap.dark.min.css created.
File tmp/css/bootstrap.light.min.css created.
File tmp/css/font-awesome.min.css created.
File tmp/css/normalize.min.css created.
File tmp/css/timepicker.css created.
File tmp/vendor/bootstrap/less/tests/css-tests.css created.

Running "ngmin:build" (ngmin) task
ngminifying tmp/app/controllers/all.js, tmp/app/controllers/dash.js, tmp/app/controllers/dashLoader.js, tmp/app/controllers/pulldown.js, tmp/app/controllers/row.js, tmp/app/directives/addPanel.js, tmp/app/directives/all.js, tmp/app/directives/arrayJoin.js, tmp/app/directives/configModal.js, tmp/app/directives/confirmClick.js, tmp/app/directives/dashUpload.js, tmp/app/directives/esVersion.js, tmp/app/directives/kibanaPanel.js, tmp/app/directives/kibanaSimplePanel.js, tmp/app/directives/ngBlur.js, tmp/app/directives/ngModelOnBlur.js, tmp/app/directives/resizable.js, tmp/app/directives/tip.js, tmp/app/services/alertSrv.js, tmp/app/services/all.js, tmp/app/services/dashboard.js, tmp/app/services/esVersion.js, tmp/app/services/fields.js, tmp/app/services/filterSrv.js, tmp/app/services/kbnIndex.js, tmp/app/services/panelMove.js, tmp/app/services/querySrv.js, tmp/app/services/timer.js, tmp/app/filters/all.js, tmp/app/panels/bettermap/leaflet/leaflet-src.js, tmp/app/panels/bettermap/leaflet/leaflet.js, tmp/app/panels/bettermap/leaflet/plugins.js, tmp/app/panels/bettermap/module.js, tmp/app/panels/column/module.js, tmp/app/panels/dashcontrol/module.js, tmp/app/panels/derivequeries/module.js, tmp/app/panels/fields/module.js, tmp/app/panels/filtering/module.js, tmp/app/panels/goal/module.js, tmp/app/panels/histogram/interval.js, tmp/app/panels/histogram/module.js, tmp/app/panels/histogram/timeSeries.js, tmp/app/panels/hits/module.js, tmp/app/panels/map/lib/jquery.jvectormap.min.js, tmp/app/panels/map/lib/map.europe.js, tmp/app/panels/map/lib/map.usa.js, tmp/app/panels/map/lib/map.world.js, tmp/app/panels/map/module.js, tmp/app/panels/query/module.js, tmp/app/panels/sparklines/interval.js, tmp/app/panels/sparklines/module.js, tmp/app/panels/sparklines/timeSeries.js, tmp/app/panels/stats/module.js, tmp/app/panels/table/module.js, tmp/app/panels/terms/module.js, tmp/app/panels/text/lib/showdown.js, tmp/app/panels/text/module.js, tmp/app/panels/timepicker/module.js, tmp/app/panels/trends/module.js, tmp/app/app.js, tmp/vendor/angular/angular-cookies.js, tmp/vendor/angular/angular-dragdrop.js, tmp/vendor/angular/angular-sanitize.js, tmp/vendor/angular/angular-strap.js, tmp/vendor/angular/angular.js, tmp/vendor/angular/bindonce.js, tmp/vendor/angular/datepicker.js, tmp/vendor/angular/timepicker.js, tmp/vendor/elasticjs/elastic-angular-client.js

Running "requirejs:build" (requirejs) task

Running "clean:temp" (clean) task
Cleaning tmp...OK

Running "build:write_revision" task

Running "git-describe:me" (git-describe) task
>> v3.0.0-126-5671213

Running "string-replace:config" (string-replace) task
File dist/app/components/require.config.js created.
File dist/app/app.js created.

Running "uglify:dest" (uglify) task
[TypeError: Cannot assign to read only property 'warnings' of true]
>> Uglifying source "dist/app/app.js" failed.
Warning: Uglification failed.
Cannot assign to read only property 'warnings' of true. 
 Use --force to continue.

Aborted due to warnings.
Build step 'Execute shell' marked build as failure
```
Test FAILed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.kibana-PRs/30/Test PASSed.

**Pull request merged**
